version: '3'

## choose wp version
## https://hub.docker.com/_/wordpress/
##
##
## choose db version
## https://hub.docker.com/_/mysql/
## or
## https://hub.docker.com/_/mariadb
##
## see
## https://github.com/docker-library/docs/tree/master/wordpress


services:
  wpdb:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wp:
    image: wordpress:4.9.2
    depends_on:
      - wpdb
    volumes:
      - ./public:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  wordmove:
    build: ./
    depends_on:
      - wp
      - wpdb
    restart: on-failure:5
    volumes:
      - ./config:/home
      - ./public:/var/www/html
      - ~/.ssh:/root/.ssh
  wpcli:
    image: wordpress:cli
    depends_on:
      - wp
      - wpdb
    restart: on-failure:5
    volumes:
      #- ./config:/home
      - ./public:/var/www/html
      - ./mysql:/var/lib/mysql
      #- ~/.ssh:/root/.ssh
    links:
      - wpdb:mysql
    entrypoint: wp  
    command: "--info"
